In [23]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import torchinfo as tinfo

In [18]:
class Model(nn.Module):
    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
    
        return out

In [25]:
class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [36]:
# with sequential container

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
        )
    
    def forward(self,features):

        out = self.network(features)

        return out

In [40]:
model = Model(5)

l1 = model.network[0]
w1 = l1.weight.data
b1 = l1.bias.data

print(w1)
print(b1)

tensor([[-0.2143, -0.3361,  0.0744,  0.3711, -0.1005],
        [ 0.3855,  0.4448,  0.0308,  0.1860,  0.4017],
        [-0.1477, -0.0637,  0.1327,  0.4101,  0.1885]])
tensor([0.2901, 0.2975, 0.4180])


In [32]:
features = torch.rand(10,5)

model = Model(features.shape[1])

out = model(features)

In [33]:
out

tensor([[0.4585],
        [0.4923],
        [0.4669],
        [0.4705],
        [0.4916],
        [0.4942],
        [0.4529],
        [0.4978],
        [0.4821],
        [0.4726]], grad_fn=<SigmoidBackward0>)

Parameter containing:
tensor([[0.2077, 0.2301, 0.3321]], requires_grad=True)

In [22]:
model.linear.bias

Parameter containing:
tensor([-0.2449], requires_grad=True)

In [30]:
tinfo.summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 22
Trainable params: 22
Non-trainable params: 0